/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author mpdha
 */
public class Internal_Assessments extends javax.swing.JFrame {

    /**
     * Creates new form Internal_Assessments
     */
    public Internal_Assessments() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        assessment_variable = new javax.swing.JLabel();
        ia_types = new javax.swing.JLabel();
        quiz = new javax.swing.JLabel();
        yes_1 = new javax.swing.JRadioButton();
        no = new javax.swing.JRadioButton();
        class_test = new javax.swing.JLabel();
        yes = new javax.swing.JRadioButton();
        no1 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        assessment_variable.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        assessment_variable.setText("Internal Assessments");

        ia_types.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ia_types.setText("Internal Assessment Types ");

        quiz.setText("1. Quiz");

        yes_1.setText("Yes");
        yes_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yes_1ActionPerformed(evt);
            }
        });

        no.setText("No");

        class_test.setText("2. Class Test");

        yes.setText("Yes");
        yes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yesActionPerformed(evt);
            }
        });

        no1.setText("No");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(quiz)
                                .addGap(18, 18, 18)
                                .addComponent(yes_1)
                                .addGap(18, 18, 18)
                                .addComponent(no))
                            .addComponent(ia_types)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(class_test)
                                .addGap(18, 18, 18)
                                .addComponent(yes)
                                .addGap(18, 18, 18)
                                .addComponent(no1))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(assessment_variable)))
                .addContainerGap(150, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(assessment_variable)
                .addGap(18, 18, 18)
                .addComponent(ia_types)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(quiz)
                    .addComponent(yes_1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(no))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(class_test)
                    .addComponent(yes)
                    .addComponent(no1))
                .addGap(111, 111, 111))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void yes_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yes_1ActionPerformed
        // TODO add your handling code here:
        Quiz q = new Quiz();
        q.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_yes_1ActionPerformed

    private void yesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yesActionPerformed
        // TODO add your handling code here:
        Class_Test c = new Class_Test();
        c.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_yesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Internal_Assessments.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Internal_Assessments.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Internal_Assessments.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Internal_Assessments.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Internal_Assessments().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel assessment_variable;
    private javax.swing.JLabel class_test;
    private javax.swing.JLabel ia_types;
    private javax.swing.JRadioButton no;
    private javax.swing.JRadioButton no1;
    private javax.swing.JLabel quiz;
    private javax.swing.JRadioButton yes;
    private javax.swing.JRadioButton yes_1;
    // End of variables declaration//GEN-END:variables
}
