/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author mpdha
 */
public class Internal_Assessments extends javax.swing.JFrame {

    /**
     * Creates new form Internal_Assessments
     */
    public Internal_Assessments() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        assessment_variable = new javax.swing.JLabel();
        ia_types = new javax.swing.JLabel();
        class_test = new javax.swing.JLabel();
        date_of_planned_assessment = new javax.swing.JLabel();
        date_assessment_p = new javax.swing.JTextField();
        date_of_conducted_assessment1 = new javax.swing.JLabel();
        date_assessment_c1 = new javax.swing.JTextField();
        result_date = new javax.swing.JLabel();
        result_declared = new javax.swing.JTextField();
        signature_student = new javax.swing.JLabel();
        yes = new javax.swing.JRadioButton();
        no1 = new javax.swing.JRadioButton();
        quiz1 = new javax.swing.JLabel();
        date_of_planned_assessment1 = new javax.swing.JLabel();
        date_assessment_p1 = new javax.swing.JTextField();
        date_of_conducted_assessment2 = new javax.swing.JLabel();
        date_assessment_c2 = new javax.swing.JTextField();
        result_date1 = new javax.swing.JLabel();
        result_declared1 = new javax.swing.JTextField();
        signature_student1 = new javax.swing.JLabel();
        yes1 = new javax.swing.JRadioButton();
        no2 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        assessment_variable.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        assessment_variable.setText("Internal Assessments");

        ia_types.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ia_types.setText("Internal Assessment Types ");

        class_test.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        class_test.setText("2. Class Test");

        date_of_planned_assessment.setText("a. Date of Planned Assessment: ");

        date_assessment_p.setText("YYYY/MM/DD");

        date_of_conducted_assessment1.setText("b. Date of Conducted Assessment: ");

        date_assessment_c1.setText("YYYY/MM/DD");

        result_date.setText("c. Result Date: ");

        result_declared.setText("YYYY/MM/DD");

        signature_student.setText("d. Signature of Students on mark sheet  ");

        yes.setText("Yes");

        no1.setText("No");

        quiz1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        quiz1.setText("1. Quiz");

        date_of_planned_assessment1.setText("a. Date of Planned Assessment: ");

        date_assessment_p1.setText("YYYY/MM/DD");

        date_of_conducted_assessment2.setText("b. Date of Conducted Assessment: ");

        date_assessment_c2.setText("YYYY/MM/DD");

        result_date1.setText("c. Result Date: ");

        result_declared1.setText("YYYY/MM/DD");

        signature_student1.setText("d. Signature of Students on mark sheet  ");

        yes1.setText("Yes");

        no2.setText("No");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(281, Short.MAX_VALUE)
                .addComponent(assessment_variable)
                .addGap(262, 262, 262))
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(class_test)
                            .addComponent(ia_types))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(date_of_planned_assessment)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(date_assessment_p, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(result_date)
                                        .addGap(18, 18, 18)
                                        .addComponent(result_declared, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(date_of_planned_assessment1)
                                .addGap(18, 18, 18)
                                .addComponent(date_assessment_p1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(result_date1)
                                .addGap(18, 18, 18)
                                .addComponent(result_declared1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(signature_student)
                                        .addGap(18, 18, 18)
                                        .addComponent(yes)
                                        .addGap(18, 18, 18)
                                        .addComponent(no1))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(date_of_conducted_assessment2)
                                        .addGap(18, 18, 18)
                                        .addComponent(date_assessment_c2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(date_of_conducted_assessment1)
                                        .addGap(18, 18, 18)
                                        .addComponent(date_assessment_c1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(signature_student1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(yes1)
                                .addGap(18, 18, 18)
                                .addComponent(no2)
                                .addGap(75, 75, 75))))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(70, 70, 70)
                    .addComponent(quiz1)
                    .addContainerGap(665, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(assessment_variable)
                .addGap(18, 18, 18)
                .addComponent(ia_types)
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(date_of_planned_assessment)
                    .addComponent(date_assessment_p, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(date_of_conducted_assessment1)
                    .addComponent(date_assessment_c1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(result_date)
                    .addComponent(result_declared, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(signature_student1)
                    .addComponent(yes1)
                    .addComponent(no2))
                .addGap(26, 26, 26)
                .addComponent(class_test)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(date_of_planned_assessment1)
                    .addComponent(date_assessment_p1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(date_of_conducted_assessment2)
                    .addComponent(date_assessment_c2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(result_date1)
                    .addComponent(result_declared1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(signature_student)
                    .addComponent(yes)
                    .addComponent(no1))
                .addContainerGap(75, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(125, 125, 125)
                    .addComponent(quiz1)
                    .addContainerGap(262, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Internal_Assessments.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Internal_Assessments.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Internal_Assessments.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Internal_Assessments.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Internal_Assessments().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel assessment_variable;
    private javax.swing.JLabel class_test;
    private javax.swing.JTextField date_assessment_c1;
    private javax.swing.JTextField date_assessment_c2;
    private javax.swing.JTextField date_assessment_p;
    private javax.swing.JTextField date_assessment_p1;
    private javax.swing.JLabel date_of_conducted_assessment1;
    private javax.swing.JLabel date_of_conducted_assessment2;
    private javax.swing.JLabel date_of_planned_assessment;
    private javax.swing.JLabel date_of_planned_assessment1;
    private javax.swing.JLabel ia_types;
    private javax.swing.JRadioButton no1;
    private javax.swing.JRadioButton no2;
    private javax.swing.JLabel quiz1;
    private javax.swing.JLabel result_date;
    private javax.swing.JLabel result_date1;
    private javax.swing.JTextField result_declared;
    private javax.swing.JTextField result_declared1;
    private javax.swing.JLabel signature_student;
    private javax.swing.JLabel signature_student1;
    private javax.swing.JRadioButton yes;
    private javax.swing.JRadioButton yes1;
    // End of variables declaration//GEN-END:variables
}
