/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package home;

import utils.DatabaseConnectivity;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;

/**
 *
 * @author Rutu Bhanderi
 */
public class FacultyInfo extends javax.swing.JFrame {

    /**
     * Creates new form FacultyInfo_draft
     */
    public FacultyInfo() {
        initComponents();
       
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        proNameComboBox = new javax.swing.JComboBox<>();
        semComboBox = new javax.swing.JComboBox<>();
        natureComboBox = new javax.swing.JComboBox<>();
        departmentname = new javax.swing.JLabel();
        batchYr = new javax.swing.JLabel();
        instituteName = new javax.swing.JTextField();
        facTextField1 = new javax.swing.JTextField();
        fac_typeComboBox1 = new javax.swing.JComboBox<>();
        facTextField2 = new javax.swing.JTextField();
        fac_typeComboBox2 = new javax.swing.JComboBox<>();
        facTextField3 = new javax.swing.JTextField();
        fac_typeComboBox3 = new javax.swing.JComboBox<>();
        batchComboBox = new javax.swing.JComboBox<>();
        deptComboBox = new javax.swing.JComboBox<>();
        saveButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        nextButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(0, 0));

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 125));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("Faculty Info");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(299, 42, -1, -1));

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setBackground(new java.awt.Color(204, 255, 204));

        jLabel2.setText("Institute Name:");

        jLabel3.setText("Faculty Name:");

        jLabel4.setText("Faculty Type:");

        jLabel5.setText("Programme:");

        jLabel6.setText("Semester:");

        proNameComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "B.Tech.", "M.Tech.", " " }));
        proNameComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proNameComboBoxActionPerformed(evt);
            }
        });

        semComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8" }));

        natureComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "UG", "PG" }));

        departmentname.setText("Name of Department");

        batchYr.setText("Batch");

        instituteName.setText("SIT");
        instituteName.setEnabled(false);

        facTextField1.setToolTipText("faculty 1");

        fac_typeComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Full Time", "Visiting", "Adjunct", " " }));

        facTextField2.setToolTipText("faculty 2");

        fac_typeComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Full Time", "Visiting", "Adjunct" }));

        facTextField3.setToolTipText("faculty 3");

        fac_typeComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Full Time", "Visiting", "Adjunct" }));

        batchComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2020-24", "2021-25", "2022-26", "2023-27" }));

        deptComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CE", "CSE", "ENTC", "ME", "AIML ", "RNA", "GST", "ES", "ED", "AT ", " " }));

        saveButton.setText("Save");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        backButton.setText("Back");

        nextButton.setText("Next");
        nextButton.setEnabled(false);
        nextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(instituteName, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(departmentname)
                        .addGap(51, 51, 51)
                        .addComponent(deptComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(23, 23, 23)
                        .addComponent(facTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(facTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(facTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(30, 30, 30)
                        .addComponent(fac_typeComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(fac_typeComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(fac_typeComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(28, 28, 28)
                        .addComponent(proNameComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(natureComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(142, 142, 142)
                        .addComponent(batchYr)
                        .addGap(18, 18, 18)
                        .addComponent(batchComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(43, 43, 43)
                        .addComponent(semComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(172, 172, 172)
                .addComponent(backButton)
                .addGap(122, 122, 122)
                .addComponent(saveButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(nextButton)
                .addGap(140, 140, 140))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(instituteName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deptComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(departmentname))))
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel3))
                    .addComponent(facTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(facTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(facTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel4))
                    .addComponent(fac_typeComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fac_typeComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fac_typeComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(proNameComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(natureComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(batchYr))
                    .addComponent(batchComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel6))
                    .addComponent(semComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backButton)
                    .addComponent(saveButton)
                    .addComponent(nextButton))
                .addContainerGap(61, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
         try{
            Connection conn = DatabaseConnectivity.connectDatabase();
            //getting data
            String iname=instituteName.getText();
            String dept=(String)deptComboBox.getSelectedItem();
            String fac1=facTextField1.getText();
            String fac2=facTextField2.getText();
            String fac3=facTextField3.getText();
            String factype1=(String)fac_typeComboBox1.getSelectedItem();
            String factype2=(String)fac_typeComboBox2.getSelectedItem();
            String factype3=(String)fac_typeComboBox3.getSelectedItem();
            String pro=(String)proNameComboBox.getSelectedItem();
            String nat=(String)natureComboBox.getSelectedItem();
            String batch=(String)batchComboBox.getSelectedItem();
            Integer sem =Integer.valueOf((String)semComboBox.getSelectedItem());
            
            String q1="INSERT INTO table_form_1 (form_id,name_of_institute,name_of_department,name_of_programme,nature_of_programme,semester,batch)"
                    + "values(?,?,?,?,?,?,?);";
            String q2="INSERT INTO table_form_faculty (form_id,name_of_faculty,faculty_type)"
                    + "values(1,?,?),(1,?,?),(1,?,?);";
            PreparedStatement pstmt = conn.prepareStatement(q1);
                pstmt.setInt(1, 1);
                pstmt.setString(2,iname);
                pstmt.setString(3, dept);
                pstmt.setString(4, pro);
                pstmt.setString(5,nat);
                pstmt.setInt(6,sem);
                pstmt.setString(7,batch);
             
             PreparedStatement pstmt1 = conn.prepareStatement(q2);
                pstmt1.setString(1,fac1);
                pstmt1.setString(2,factype1);
                pstmt1.setString(3,fac2);
                pstmt1.setString(4,factype2);
                pstmt1.setString(5,fac3);
                pstmt1.setString(6,factype3);
                
                int rowsUpdated1=pstmt.executeUpdate(); 
                int rowsUpdated2=pstmt1.executeUpdate();
                        if (rowsUpdated1 > 0 && rowsUpdated2>0) {
                            JOptionPane.showMessageDialog(rootPane, "Saved successfully.", 
                                    "Success", JOptionPane.INFORMATION_MESSAGE);
                            nextButton.setEnabled(true);
                            
                        } else {
                            JOptionPane.showMessageDialog(rootPane, 
                                    "Failed to save details.", 
                                    "Error", JOptionPane.ERROR_MESSAGE);
                        }
       
             
         }catch(Exception e){
             e.printStackTrace();
         }
        nextButton.setEnabled(true);        // TODO add your handling code here:
    }//GEN-LAST:event_saveButtonActionPerformed

    private void nextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextButtonActionPerformed
        new Course().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_nextButtonActionPerformed

    private void proNameComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proNameComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_proNameComboBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FacultyInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FacultyInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FacultyInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FacultyInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FacultyInfo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JComboBox<String> batchComboBox;
    private javax.swing.JLabel batchYr;
    private javax.swing.JLabel departmentname;
    private javax.swing.JComboBox<String> deptComboBox;
    private javax.swing.JTextField facTextField1;
    private javax.swing.JTextField facTextField2;
    private javax.swing.JTextField facTextField3;
    private javax.swing.JComboBox<String> fac_typeComboBox1;
    private javax.swing.JComboBox<String> fac_typeComboBox2;
    private javax.swing.JComboBox<String> fac_typeComboBox3;
    private javax.swing.JTextField instituteName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JComboBox<String> natureComboBox;
    private javax.swing.JButton nextButton;
    private javax.swing.JComboBox<String> proNameComboBox;
    private javax.swing.JButton saveButton;
    private javax.swing.JComboBox<String> semComboBox;
    // End of variables declaration//GEN-END:variables
}
