package home;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author mpdha
 */
import java.awt.Color;
import java.util.List;
import java.util.ArrayList;

import javax.swing.JOptionPane;
public class Internal_Assessments extends javax.swing.JFrame {
    
    /**
     * Creates new form Internal_Assessments
     */
    public Internal_Assessments() {
        initComponents();
        getContentPane().setBackground(new Color(243, 229, 143)); // Light yellow
        
        //green for buttons
        SaveButton.setBackground(new java.awt.Color(152, 255, 152)); // Light green
        SaveButton.setForeground(new java.awt.Color(0, 0, 0));
        Addbutton.setBackground(new java.awt.Color(152, 255, 152)); // Light green
        Addbutton.setForeground(new java.awt.Color(0, 0, 0));
        PreviousButton.setBackground(new java.awt.Color(152, 255, 152)); // Light green
        PreviousButton.setForeground(new java.awt.Color(0, 0, 0));

    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jFrame2 = new javax.swing.JFrame();
        jFrame3 = new javax.swing.JFrame();
        assessment_variable = new javax.swing.JLabel();
        ia_types = new javax.swing.JLabel();
        quizCheckBox = new javax.swing.JCheckBox();
        classTestjCheckBox = new javax.swing.JCheckBox();
        labTestjCheckBox = new javax.swing.JCheckBox();
        caseStudyjCheckBox = new javax.swing.JCheckBox();
        assignmentCheckBox = new javax.swing.JCheckBox();
        presentationjCheckBox = new javax.swing.JCheckBox();
        miniProjectjCheckBox = new javax.swing.JCheckBox();
        whitePaperjCheckBox = new javax.swing.JCheckBox();
        SaveButton = new javax.swing.JButton();
        Addbutton = new javax.swing.JButton();
        PreviousButton = new javax.swing.JButton();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame2Layout = new javax.swing.GroupLayout(jFrame2.getContentPane());
        jFrame2.getContentPane().setLayout(jFrame2Layout);
        jFrame2Layout.setHorizontalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame2Layout.setVerticalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame3Layout = new javax.swing.GroupLayout(jFrame3.getContentPane());
        jFrame3.getContentPane().setLayout(jFrame3Layout);
        jFrame3Layout.setHorizontalGroup(
            jFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame3Layout.setVerticalGroup(
            jFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        assessment_variable.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        assessment_variable.setText("Internal Assessments");

        ia_types.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ia_types.setText("Select assessment type");

        quizCheckBox.setText("Quiz");
        quizCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quizCheckBoxActionPerformed(evt);
            }
        });

        classTestjCheckBox.setText("Class Test");

        labTestjCheckBox.setText("Lab Test");

        caseStudyjCheckBox.setText("Case Study");

        assignmentCheckBox.setText("Assignment");

        presentationjCheckBox.setText("Presentation");
        presentationjCheckBox.setToolTipText("");

        miniProjectjCheckBox.setText("Mini Project");
        miniProjectjCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miniProjectjCheckBoxActionPerformed(evt);
            }
        });

        whitePaperjCheckBox.setText("White Paper");
        whitePaperjCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                whitePaperjCheckBoxActionPerformed(evt);
            }
        });

        SaveButton.setText("Save");
        SaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveButtonActionPerformed(evt);
            }
        });

        Addbutton.setText("Add");
        Addbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddbuttonActionPerformed(evt);
            }
        });

        PreviousButton.setText("Previous");
        PreviousButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PreviousButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(219, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(PreviousButton)
                        .addGap(75, 75, 75)
                        .addComponent(Addbutton)
                        .addGap(75, 75, 75)
                        .addComponent(SaveButton)
                        .addGap(212, 212, 212))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(miniProjectjCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(whitePaperjCheckBox)
                            .addComponent(presentationjCheckBox)
                            .addComponent(assignmentCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(271, 271, 271))))
            .addGroup(layout.createSequentialGroup()
                .addGap(267, 267, 267)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(classTestjCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(quizCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(assessment_variable)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(57, 57, 57)
                                .addComponent(ia_types)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labTestjCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(caseStudyjCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(assessment_variable)
                .addGap(28, 28, 28)
                .addComponent(ia_types)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(quizCheckBox)
                    .addComponent(assignmentCheckBox))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(classTestjCheckBox)
                    .addComponent(presentationjCheckBox))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labTestjCheckBox)
                    .addComponent(miniProjectjCheckBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(whitePaperjCheckBox)
                    .addComponent(caseStudyjCheckBox))
                .addGap(71, 71, 71)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SaveButton)
                    .addComponent(Addbutton)
                    .addComponent(PreviousButton))
                .addGap(95, 95, 95))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
     

    private void SaveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveButtonActionPerformed
        
    }//GEN-LAST:event_SaveButtonActionPerformed

    private void whitePaperjCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_whitePaperjCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_whitePaperjCheckBoxActionPerformed

    private void quizCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quizCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quizCheckBoxActionPerformed
public  List<String> getSelectedAssessments() {
    
        List<String> selectedAssessments = new ArrayList<>();
        if (quizCheckBox.isSelected()) {
            selectedAssessments.add("Quiz");
        }
        if (assignmentCheckBox.isSelected()) {
            selectedAssessments.add("Assignment");
        }
        if (labTestjCheckBox.isSelected()) {
            selectedAssessments.add("Lab Test");
        }
        if(caseStudyjCheckBox.isSelected())
         {
             selectedAssessments.add("Case Study");
         }
           if(classTestjCheckBox.isSelected())
         {
            selectedAssessments.add("Class Test");
         }
          if(miniProjectjCheckBox.isSelected())
         {
             selectedAssessments.add("Mini Project");
         }
          if(presentationjCheckBox.isSelected())
         {
             selectedAssessments.add("Presentation");
         }
          if(whitePaperjCheckBox.isSelected())
         {
             selectedAssessments.add("White Paper");
         }
         
        
        return selectedAssessments;
    }
    private void AddbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddbuttonActionPerformed
      List<String> selectedAssessments = getSelectedAssessments();
        if (!selectedAssessments.isEmpty() && selectedAssessments.size() <= 4) {
            // Close the Internal_Assessments frame
        } else {
            JOptionPane.showMessageDialog(null, "Please select an internal assessment.");
        }
    }//GEN-LAST:event_AddbuttonActionPerformed

    private void PreviousButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PreviousButtonActionPerformed
        Course c= new Course();
        c.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_PreviousButtonActionPerformed

    private void miniProjectjCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miniProjectjCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_miniProjectjCheckBoxActionPerformed
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Internal_Assessments.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Internal_Assessments.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Internal_Assessments.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Internal_Assessments.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Internal_Assessments().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Addbutton;
    private javax.swing.JButton PreviousButton;
    private javax.swing.JButton SaveButton;
    private javax.swing.JLabel assessment_variable;
    private javax.swing.JCheckBox assignmentCheckBox;
    private javax.swing.JCheckBox caseStudyjCheckBox;
    private javax.swing.JCheckBox classTestjCheckBox;
    private javax.swing.JLabel ia_types;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JFrame jFrame2;
    private javax.swing.JFrame jFrame3;
    private javax.swing.JCheckBox labTestjCheckBox;
    private javax.swing.JCheckBox miniProjectjCheckBox;
    private javax.swing.JCheckBox presentationjCheckBox;
    private javax.swing.JCheckBox quizCheckBox;
    private javax.swing.JCheckBox whitePaperjCheckBox;
    // End of variables declaration//GEN-END:variables
}
