/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package home;

import utils.DatabaseConnectivity;
import java.sql.PreparedStatement;
import utils.Validations;
import java.sql.Statement;
import java.sql.Connection;
import javax.swing.JOptionPane;
import java.sql.ResultSet;
import java.sql.SQLException;

/**
 *
 * @author Rutu Bhanderi
 */
public class SignUp extends javax.swing.JFrame {
        
    /**
     * Creates new form SignUp
     */
    public SignUp() {
        initComponents();
        setSize(800,500);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        nameTextField = new javax.swing.JTextField();
        emailTextField = new javax.swing.JTextField();
        newpassField = new javax.swing.JPasswordField();
        reenteredpassField = new javax.swing.JPasswordField();
        SignUpButton = new javax.swing.JButton();
        BackButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 140));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Sign Up");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 50, -1, -1));

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setBackground(new java.awt.Color(204, 255, 204));
        jPanel2.setPreferredSize(new java.awt.Dimension(800, 360));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Name:");
        jLabel2.setToolTipText("");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 40, -1, -1));

        jLabel3.setText("Email / Username:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 80, -1, -1));

        jLabel4.setText("New Password:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 120, -1, -1));

        jLabel5.setText("Re-enter New Password:\n");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 160, -1, -1));
        jPanel2.add(nameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 40, 110, -1));
        jPanel2.add(emailTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 80, 110, -1));
        jPanel2.add(newpassField, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 120, 110, -1));
        jPanel2.add(reenteredpassField, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 160, 110, -1));

        SignUpButton.setText("Sign Up");
        SignUpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignUpButtonActionPerformed(evt);
            }
        });
        jPanel2.add(SignUpButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 210, -1, -1));

        BackButton.setText("Back");
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });
        jPanel2.add(BackButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 210, -1, -1));

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void SignUpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignUpButtonActionPerformed
        Connection conn = DatabaseConnectivity.connectDatabase();
        if(conn!=null){
            try{
            
            Statement stmt = conn.createStatement();
            String name = nameTextField.getText();
            if(name.length()!=0){
                String email = emailTextField.getText();                              
                if(Validations.isEmailValid(email)){
                        //query
                       String query  ="select faculty_Email from faculty where faculty_Email='"+email+"';";
                       ResultSet rs=stmt.executeQuery(query); 
                       if(!rs.next()){
                           String userpass1 = String.valueOf(newpassField.getPassword());
                           if(Validations.isPasswordValid(userpass1))
                           {
                            String userpass2 = String.valueOf(reenteredpassField.getPassword()); 
                            if(userpass1.equals(userpass2)){
                                String query1 ="insert into faculty (faculty_name,faculty_Email,Password) values(?,?,?)";
                                try (PreparedStatement pstmt = conn.prepareStatement(query1)) {
                                pstmt.setString(1, name);
                                pstmt.setString(2, email);
                                pstmt.setString(3, userpass1);
                                pstmt.executeUpdate();
                                    JOptionPane.showMessageDialog(rootPane, "Account created successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
                                new SignIn().setVisible(true);
                                this.dispose();
                            }              
                             catch (Exception e) {
                                 JOptionPane.showMessageDialog(rootPane, "Account creation unsuccessfull!", "Error", JOptionPane.INFORMATION_MESSAGE);
                            }
                            }
                            else{
                                JOptionPane.showMessageDialog(rootPane, "Passwords are not equal.", 
                                            "Input Error", JOptionPane.ERROR_MESSAGE);
                            }
                           }else{
                               JOptionPane.showMessageDialog(rootPane, """
                                                                        Password must be 8 characters long and must contain
                                                                        - 1 capital letter
                                                                        - 1 small letter
                                                                        - 1 special character
                                                                        - 1 number.""", 
                                        "Input Error", JOptionPane.ERROR_MESSAGE);
                           }
                       }else{
                           JOptionPane.showMessageDialog(rootPane, "Email is already taken, try a different email.", 
                                    "Unvailable", JOptionPane.ERROR_MESSAGE);
                       }
                        }else{
                    JOptionPane.showMessageDialog(rootPane, "Email is invalid.", 
                                            "Input Error", JOptionPane.ERROR_MESSAGE);
                }
            }else{
                 JOptionPane.showMessageDialog(rootPane, "Name cannot be empty.", 
                                    "Input Error", JOptionPane.ERROR_MESSAGE);
            }
            }
            catch(SQLException e){
                JOptionPane.showMessageDialog(rootPane, "SQL Error: " + e.getMessage(),
                        "Database Error", JOptionPane.ERROR_MESSAGE);
                }
            catch(Exception e){
                JOptionPane.showMessageDialog(rootPane, "An error occurred: " + e.getMessage(),
                        "Unknown Error", JOptionPane.ERROR_MESSAGE);
                    }
            }
         DatabaseConnectivity.closeConnection(conn);
   
    

            
    }//GEN-LAST:event_SignUpButtonActionPerformed

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        new Main().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BackButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignUp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackButton;
    private javax.swing.JButton SignUpButton;
    private javax.swing.JTextField emailTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JPasswordField newpassField;
    private javax.swing.JPasswordField reenteredpassField;
    // End of variables declaration//GEN-END:variables
}
